window.onload = function () {
  document
    .getElementById("pushQuote")
    .addEventListener("click", pushQuoteClick, false);

  var newLocal = "demo";

  function pushQuoteClick() {
    var useQuotes = [
      '"Curiosity," barked the Wolf. And then the Cat died.',
      'The Lion said, "Mind if I sweep the corners of your round hut?"',
      'Monkey eyed Monkey warily until one suggested, "There are no ants on... my stick."',
      'Puffin shook his head sadly. No sale today.',
      '"We sharpened our cricket bats into swords," Woolly Bat said, "and sailed off to war."',
      'Maltese worried about the wind.  The wind that always brings the dust.',
      "Pig was happy with his quorum; the Goat would have to go.",
      '"Are we not men?" Mouse roared upon the gathering crowd.',
      "Mole blinked furiously in the rain and thought, I should have brought an umbrella to the bus station.",
      'Boat becalmed for days, posited by the gunwales, Owl and Fox finally leveled with each other. "That leg is getting a bit gamy, isn\'t it?"',
      "Horse knew with certainty they were coming to overthrow him but he continued to deal the cards anyhow.",
      "Squirrel looked at his nuts with grave concern; this was making him very nervous.",
      'Russian Blue stuffed his hankerchief away and straightened his tie. I need a new hat."',
      'Surveying the remnants of her command Cat sighed, "We perish so that others may live."',
      '"Ladies, please," Bull admonished the nearly rioting Geese, "there is no call for such behavior."',
      'Walrus looked up from wiping down the bar, "Avast mateys, there be a Sea Cow what could dent a rotor blade!"',
      'Tortoise sipped his tea as he considered Hare\'s question, "Evolution and entropy, my old friend, evolution and entropy."',
      "Goat left and Turkey, too. Together they styled themselves as two gentle creatures of the road.",
      '"You\'re a jerk!" Turkey finally spat out, but Chipmunk simply shrugged it off and scampered on his way.',
      '"Sink me, Musk Ox thought. "One did not think it possible to get silk at such prices!"',
      'Filthy water, filthier mud, a leaden sky that wept, the trench was their whole world. Bulldog spat, "We will not be missed."',
      '"Light is fading," Rabbit told Vole, "we\'ll camp here. Be a good chap and get the fire going."',
      'Elephant glanced around the boardroom nervously, "Look, I\'ll do whatever you want. Say whatever you want. The rest will follow. Just, keep feeding me peanuts."',
      '"What Ass took my parking space?" Stoat shouted. Donkey put his head on his desk. Would this guy never leave him alone?',
      'Hippopotamus waited backstage for her cue with heart pounding and tap shoes tied too tight. "This is going to be my big night!"',
      'French Lop took a couple of steps. Then a few more. "Dancing. Check."',
      'Marmoset tapped his pencil on his notepad. "So, indoctrination and brainwashing. What\'s the real difference?"',
      'Koala lowered his binoculars. "All ahead full. Sound general quarters."',
      'Golden Glavcot brought the little troupe to a halt. "Best put on those sunglasses from here."',
      'Yak watched the roller derby intently while feigning indifference. "As if."',
      'Stork cocked his head and gave Gorilla a one-eyed look. "Go ahead. Fling it. See what happens then."',
      'Wolverine was perplexed by the myriad choices of silverware. "A girl should only have to choose once in life I should think."',
      'Tiger knitted placidly as the jungle burned all around. "Post not. Tweet not. Post not. Tweet not."',
      'Gopher, Mink and Warthog got off a bus in Harlem.',
      'We few, we happy few, thought Bear before launching himself out the side of the aircraft and plunging away into the darkness.',
      'Giraffe, skillfully guiding the little boat down the Thames, whispered to his charges, "Quiet now, we\'ll be under the bridge soon."',
      'Fox tapped patiently at the typewriter in pursuit of the greatest novel of all time.',
      'Despite the obvious danger, Moose stood high on the rampart, "Steady on, make every shot count."',
      'Badger doffed his hat and bowed low to Skunk, "I say, monsieur, one day we should look back on all this and laugh."',
      'Eagle wiped an errant tear away and brought his head up. "Forward. Today, tomorrow, always. Always forward."',
      'Armadillo scanned the faces around him, "One of us is not a team player."',
      'Dolphin smiled in surprise. "A whale? On land? That\'s ridiculous!"',
      'Deer agreed with Duck\'s assessment, "But that was long ago and in another country."',
      'Lion queried of the others, "Mind if I drink from your watering hole?"',
      'Otter singled out Boar in the group, "Are you familiar with the bishop of Norwich?"',
      'Little did Chipmunk know, watching the boats pull onto the beach, that her world would be forever changed.',
      '"Nothing," Hedgehog wiped his glasses. "Nothing plays a violin like misery."',
      'Tern yelled at Gull, "Chew, you fool, chew!" as the hotdog reappeared yet again.',
      'Panda scoffed at the absurdity. "Bah! Let them eat rice cakes then."',
      'Shrew stood firm. "Nae, none canna cross mah land widdout payin\' toll."',
      'Her eyes wide, Cheetah demurred, "Some acts one does not commit in the public eye."',
      'Lynx lectured sternly, "Grammar, spelling, and an Oxford comma may very well save your life."',
      'Magpie watched the line of orphans go by before bringing her beak down sharply on the dawdler.',
      'Gecko hooked a thumb over his shoulder, "Now then, we\'re going in that house and getting our mate, right!"',
      'From the scaffold Raccoon addressed the mob, "I\'ve done better things and gone better places than this."',
      'After crossing the field, Crow scraped the mud from his boots and knocked upon the door.',
      'Aardvark stoically persisted in leading the march though the protest had long been over.',
      '"Pinochle!" Hamster stood aghast. "Cribbage sir! I insist, sir. Cribbage is an honorable game."',
      '"Breakfast dispatched," Pony said, "we yarely meet at yon butte."',
      'Beaver cast caution to the wind and dared to eat a peach. "We do not die who choose to live!"',
      'Satin Angora wiped away the sweat between his ears. "I guess. I guess, it could actually be hotter."',
      'Baboon put a friendly arm around Puma\'s neck and remarked, "So, this is London."',
      'Coati clasped hat to chest and told his Possum, "I may not know what day it is, but I know I dream of you every night."',
      'Serval kept dancing though the band had long stopped playing as the night has a music all its own.',
      'Yelling, Toad told Dormouse, "-like driving -circles -cause -like -she says -\'recalculating\'. Ha hah!"',
      '"You talking to me?" Dodo peered into the mirror. "Are you talking to me? I don\'t see anybody else here."',
      'Aegean Cat cocked his hat to one side. "Just a penny. Just one little penny is all I ask."',
      'Echidna stirred the pot slowly. "Only a dream can kill a dream."',
      'Arabian Mau pored the coffee into small cups. "So thick, a spoon could stand upright. Or a fork."',
      'Gerbil squeaked in frustration, "There\'s no fighting in the War room, please!"',
      'Hyena stood on the sidelines in a cast; his season over before it had really begun.',
      'Lemur struck a coy pose. "If it pleases you, may I have some more?" and shyly stuck out her bowl.',
      'Kangaroo recoiled in horror. "I bally well will not, I say! Not indeed."',
      'Pixie-bob put her pearls and earrings on. "Time to paint this town red, boys!"',
      'Gazelle waited for the cover of darkness before crossing the road. She knew the cartel would be watching.',
      '"Last time I had a low country boil," Duck waggled eyebrows, "I had to see a doctor to get it lanced."',
      'Llama had never been part of a lynch mob before. It really was rather exciting.',
      '"My son will not marry a freak. We are a one hump family," Camel snapped. "Besides, they\'re probably fake."',
      'Woodchuck asked Wallaby, "Mind if I put my paw in your pocket?"',
      '"Not my fault!" Albatross proclaimed, but no one would listen and even fewer believed.',
      'With one last keystroke Bear finally booked his long awaited trip online.',
      '"After she said that," Nutria explained, "I always looked under the sheets before I got into bed."',
      '"Love on the docks," Rat sang soulfully, "ain\'t no big surprise."',
      '"My nation?" Kookaburra asked, "what is my nation?"',
      'Civet offered to pour the coffee, "It\'s my own special blend." But none accepted her generosity.',
      'Panther was afraid no one would come to his soirée but they did, and a grand time was had by all.',
      'Finally cornered, Sloth screamed, "I am not an animal! I am a, uh oh, uh yes. Yes, I suppose I am."',
      '"Now, now," Seal was stern with her class, "no one likes a nosy Narwhal. It\'s not nice."',
      '"If I thought it would make a real difference," Polecat said, "I would have proffered myself to judgement years ago."',
      'Porcupine went home with quills full of treats. It was just easier that way.',
      'The morning after, it was several minutes before Leopard realized the extra spots were bits of chocolate, caramel, and taffy.',
      'Every kit and cub checked and rechecked gear; November had come, and fortresses of leaves needed attacking.',
      'Bobcat opened the ledger and scanned the entries lazily, "Nope. No reservation, no room at the inn."',
      'Aardvark started the long march back. He had survived though no one thought he would.',
      'Gibbon thumbed through his history and found the entry. "See here, Peacock, it was not always thus."',
      '"Column A? Column B??" Guinea Pig shook with anxiety, "this could go on all day."',
      'Zebra stood defiant. "Look, our orders were to clear the square by any means necessary. We didn\'t have to like it."',
      'Ibex peered over the edge one more time. "Another one five meters to the left. He\'s yours. Ready?"',
      'Rook sat in the library alcove to peruse an excellent culinary time. With a heavy sigh, "First cutesy rhyme gets their eyes pecked out."',
      '"London calling," Mongoose mused. "And now war is declared? I suppose it\'s a collect call then?"',
      'Crowd aghast, Mandrill struggled up from riot strewn street and raised a single finger towards the glass and steel edifices.',
      'Over hill, over dale as we hit the dusty trail and the Ferrets keep rolling along.',
      'Alone, Wildebeest contemplated his mutiny. "After all, things done lightly are best not done at all. It\'s true, oh yes, it\'s true."',
      'Baboon examined his magazine in vain; the little subscription cards always drove him insane.',
      'Black Rhino squinted, "Hello? Hello anybody? Anybody out there? Is this thing on?"',
      '"Nothing like November fog," Peccary told Okapi. "Huh, why do they call it a foxhole anyways?"',
      'Ewe searched the store shelves, "Now if I were a salad dressing, what flavor salad dressing would I be?"',
      'Giraffe looked at his two companions, "I think the time has come to reconsider our agreement. The border is there, and we are not."',
      'Meerkat stopped at the hatch, "When we go through this door, good crew, we will be facing a mindless terror. Unforgiving."',
      'Nightingale lay down his accordion for the last time. "You know Papa, I think I\'ll try singing instead."',
      'Jaguar weighed her options. Would she attend the cotillion or the orphans\' charity ball? Which the better to be seen?',
      '"Elementary," deduced Heron, "the murderer has never left the room. Quickly, bring me a mop!"',
      'Komodo Dragon listened to his mate\'s haranguing and thought, she sure could use a breath mint.',
      'Pheasant sat back in his easy chair to read the paper. "Days like this make me thankful I\'m me."',
      'The conspirators huddled under a single bulb. Capybara said, "They will remember this day. This black day."',
      'Tasmanian Devil picked up the morning paper and milk bottle off the stoop before going in to breakfast. "Lovely day, really."',
      'With heavy tread Elk ascended the 39 steps. "Woe that it should be, times have come to this."',
      'Chimpanzee turned off the TV in disgust, "Why is it always my business? What business do they mean?"',
      'Pika hiked blindly through the Himalayan pass. "Let\'s travel she said. Go exotic she said. I wanted to go to Vail."',
      'Diligent and methodical, Prairie Dog stacked each bag of sand just so. "No good will come of this," he sighed.',
      'Choosing carefully from her closet, Artic Fox decided. "Today it\'s winter coat."',
      'Polar Bear lay back on the drifting ice floe and wishfully thought, maybe this time -- Havana.',
      'Horned toad finally realized, maybe I was just born that way.',
      'Mockingbird poked at the tender spot in his conscience, I really need to get that removed.',
      'Poodle examined the state the musketeers left him in. "Mercy, I guess that answers that question."',
      'Eyes just beginning to water, Harp Seal clung to her little cardboard sign; cute wouldn\'t cut it anymore.',
      '"Quickly now," Lemming ushered everyone to the fire exit. "Keep calm, and mind the gap."',
      '"Everyone told me I was ugly growing up," Swan hissed bitterly. "So I cut them."',
      'Gnu raised a toast, "Here\'s to Mother Nature who abhors a vacuum, and is none to keen on a mop either."',
      'Chicken never thought of citrus after that day. That black day.',
      'Red nose gone dark, his lifeless body lay cooling in the snow. The other Reindeer were through playing games.',
      'Turkey Vulture poured another bourbon. "I set bad examples in hopes no one will follow them."',
      'Spittle flying, ears and tail streaming, St. Bernard sprinted across the sand. "I forgot the sunblock. I forgot the sunblock."',
      'Pangolin hurried home with his prize. Spelling was never his strong suit; now maybe others would listen to him when he posted comments.',
      'Bluetick Coonhound studied the darkened string intently. "One bulb. But which bulb?"',
      '"There it is again," Caribou said excitedly. "Do you smell it? It\'s a yellow smell. It smells of... death."',
      'Toucan told Crocodile, "You\'re cold blooded. Of course butter doesn\'t melt in your mouth."',
      '"Last night I shot an Elephant in my pajamas." Ostrich buried his head. "The horror. The horror."',
      'Ocelot gripped his attaché tighter. "These are the times for which bureaucratic paper shuffling is no defense."',
      'Sugar Baby popped up from the pot she was cleaning. "Oh no. No one matriculates in my kitchen. You\'ll be scrubbing floors on your- What?"',
      'Pine Marten demonstrated for her etiquette class, "Now hang the roll this way and it is a subtle hint for your guests to go home."',
      'Impala checked the train schedule one more time. He didn\'t want to be late for holiday on the veldts.',
      'Sparrow, when asked if archery is an aerobic exercise, replied, "Only if you\'re the target."',
      'Persian gazed at the mass of paper, ribbons, and bows tiredly. "Some days there\'s not enough sand in the cat box."',
      '"It\'s got snacks on string!" Cardinal made his pitch. "Look, my love, it\'s a rather pretty tree. What with the lights and all."',
      'With a dramatic sweep of her tail and a toss of her head, Jerboa climbed the grand staircase leaving everyone speechless.',
      'Porpoise slipped under the hull and surfaced between ship and dock to cut the mooring lines. No one would be leaving the island today.',
      'Egret stared into the distance of the marsh. And stared. And stared. For a thousand yards he stared; blood dripped from the tip of his beak.',
      '"Is it really that important to be recognized?" Vicuña wondered. "What of work being its own reward?"',
      'Snipe ghosted through the crowd like he didn\'t exist at all. Sometimes his work was just too easy.',
      'Alpaca hung up his knapsack for the last time. No more adventuring since the arrow hit him in the knee.',
      'Partridge awoke to a sound and fury. A sound and fury that existed only in her head.',
      'Leaving the doctor\'s office, Zebu paused to reflect. Tomorrow things would change and change forever after.',
      'Back at his desk, Siberian Tiger eyed the piles of waiting paperwork and rued the day he moved to management.',
      'Oryx addressed the hospital tent from his cot, "Speaking of those that would bleed with me this day, I meant figuratively."',
      'Pygmy Slow Loris peeped up from behind a closed door, "When we run out of paper I feel I\'m flushing the last of my dignity down the drain."',
      '"Socialism?" Kinkajou convulsed with laughter. "You idiots wouldn\'t know socialism if it slapped you with a little red notebook."',
      'Sometimes life can be uncomfortable, Gemsbok explained, "sort of like, ill-fitting underwear."',
      'The room\'s attention riveted, Cormorant continued, "And there in the rigging of the topsail I lost my leg."',
      'Pomeranian pulled the bolt on the Maxim gun and readied for the day\'s hot work.',
      '"Me having a go at poetry," Finch said, "is like bringing a dull shiv to a prison of writer\'s blocks."',
      'Cradling Wren\'s head in her lap, Grizzly gently held his soul and wept. "We\'ll always have Paris."',
      'Sable points at a map."The enemy are here, here and here. And here. And here. Bloody hell, this is my seating for dinner with the in-laws!"',
      'Newt pounded the podium. "I can\'t promise a Chicken in every pot, but only because I don\'t speak for the Chickens."',
      '"Woe to be leaving England all covered in snow," Condor thought. "Woe to be weary of spirits running low." And he shook the empty little bottle.',
      'Flying Squirrel checked her luggage at an exorbitant price and cursed the day the Sparrow Hawk brothers got off the ground.',
      'Mallard confessed, "The last time I forced a rhyme I spent thirty days in the hole."',
      'Jackrabbit pushed the empty glass back across the bar. "We don\'t hold with that kind of talk around here, pilgrim."',
      'Beagle took a stand. "Laws are meant to confine the lawless, not curtail the activities of the lawful."',
      '"We will wait here," Musk Deer said. "We will wait for the one who comes to tell us of far Verona."',
      'Woodpecker put his newspaper down. "Editorials. Makes me miss the days of torches and pitchforks. What\'s it take to get an angry mob now?"',
      'Chihuahua glared at the mirror wearing the sweater his wife gave him and realized no one bites back as hard on their anger.',
      'Hoist the yellow flag, Boxer growled. "No port will have us now."',
      'Miller\'s Grizzled Langur didn\'t just pose for the camera, she spoke to it. She sang to it. She gave it that extra dimension-- life.',
      '"When I eat my weight in popcorn," Blue Whale explained coming out of the theater, "I qualify for a farm subsidy."',
      'Ermine lay in the mud looking up at at a weeping sky. He would miss croissants, brie, and fools that might be king. But not English arrows.',
      'Brown Bear shifted in his seat in the audience. "I hate poets. And their reading. Make every word sound like they just invented it. Verily."',
      'Aye-aye idly stirred his coffee at the cafe table and waited for traffic to die down. Assassinations should never be rushed.',
      'Red Fox watched her designs go down the runway to blaring music and flashing bulbs. "First one that trip gets throat cut, darlings."',
      'Bantam Rooster spoke from his fence post perch, "Nothing I like better than watching chicks beat the crap out of each other." And he spat.',
      '"Abba dabba," was all Chimpanzee managed to get out before Spider Monkey cold cocked him.',
      'Gingerly, Chinese Crested pulled the hood of his cloak back up, "I\'m sorry. I\'m sorry you had to see that. I thought you should know."',
      'Tasmanian Devil stopped the elevator. "Eighth floor moneylenders, bankers, brokers, financial wizards, and grifters. Next floor, lawyers."',
      'Trying desperately to appear unimpressed by Constantinople, Bonobo insisted on referring to the city as simply, "Stan."',
      'Dhole fumbled his reload as the mob surged up the steep stairs. "Peachy. Just flippin\' peachy."',
      'Cornbread and butterbeans, Harlequin Bat sang softly on his way back to his date. "I have the tickets, dear. Let\'s go see the opera."',
      'Abyssinian slammed down the phone. "What do they mean by no betting on the second half?"',
      'Cape Hare darted in out of the rain. "Dash it all, I bloody well won\'t be selling many matches in this weather."',
      'Caracal spat out food in complete surprise. "Fix bayonets?!? I just fixed my lunch!"',
      'Malayan Sun Bear appealed to the court. "There are no bad lawyers, only a dearth of worthwhile clients."',
      '"I never could get work at the factory," Leaf-nosed Bat complained. "I couldn\'t bear the noise."',
      'Wire Fox Terrier felt secure in his position as king amongst others but, not so sure of his place on the furniture.',
      'Armenian Hamster ran down his daily mantra, "Cover butt. Feed butt. Get shelter for butt."',
      '"Merde," Sloth Bear complained. "I\'d lose my own head if I thought there was a revolution in it."',
      '"My purview," Blandford\'s Fox defined, "is much the same as my domain, only sexier."',
      'Tibetan Gazelle kissed his sleeping mate goodbye and left for the office. Mountains do not climb themselves.',
      '"Pekingese!" Bluetick Coonhound spluttered at the TV. "I\'ve got blood gorged fleas with more dog in them that thing." And poured bourbon.',
      'Himalayan Mole stubbed out his cheroot and took a slow walk around the plane. "I\'ll either be famous when this is over or very, very dead."',
      '"Why could I not be made of sponge like you?" Humpback Dolphin asked the little cake.',
      'Nicobar Treeshrew packed his bags and grabbed his hat. He wanted to meet the taxi at the curb before the driver honked.',
      '"Whatever shall I do to warrant his affection?" Hoolock Gibbon fretted. She soon perked up. "I know. I shall write him a letter."',
      '"Perhaps I\'m wrong," Hog Badger admitted. "But shouldn\'t any really civilized debate contain some modicum of intelligence?"',
      '"Why should they call it zero hour?" Toddy Cat watched his second hand sweep round. "It always comes with a price, if you ask me."',
      'Dugong held up both boxes. "One box, and one box only, holds a prize. The other, just a dream. But which is the greater?"',
      'Ratel rushed from the latrines. "Sorry, sorry. Simple ceremony turned into a full blown religious experience. Ha ha."',
      '"I\'ve just been to market," Vietnamese Pot Belly looked cross at her mate. "What? What are you laughing at?"',
      'Golden Jackal led the group a merry chase before finally coming to rest in a hedgerow. At nightfall, he slipped free and made a dash for it.',
      'Spotted Linsang braked hard and pulled over to the side of the road. "Ack, I left my wallet in El Segundo."',
      '"The drums have stopped." House Mouse paused to listen. "Oh, my bad. They\'re just between sets."',
      'Red-necked Wallaby stood by the loch and counted out his spare change. "Three pound fifty. Well, how fortunate is that?"',
      'I didn\'t leave my heart in San Francisco, Hooded Seal admitted, "but I did leave some nail clippings in Bristol."',
      'Natterer\'s Bat looked at her sad, self-published memoir. "My whole life story consists of bowel movements and coupon cutting."',
      '"Tally the ballots, my friends," Mountain Hare ordered. "It is time to see where we spend our leisure this year."',
      'Eurasian Beaver checked his timepiece and put it back in his waistcoat pocket. "Trains. I should have taken the flume."',
      '"He\'ll never change," Water Vole opined. "It\'s like the preservation society has hold of that facade of his and won\'t let it be torn down."',
      'Nathusius Pipistrelle finished off his newest translation of Oneirocritica before blowing out the candles and retiring to the Bed of Sphinx.',
      'Bilberry Goat felt incredibly slighted that for certain others it only took three full bags to get by in life.',
      '"A cup of sack with lime?" Sika Deer eyed the tavern keep. "Can I get a little umbrella, too?"',
      'Red Squirrel banged his gavel for attention. "Let\'s get this party started. I brought my seven layer dip."',
      '"Some species eat their young," Edible Dormouse mimicked. "If I have to hear that one more time..."',
      'Brown Rat squinted at her clock with deep suspicion. "You\'ve changed. I know you changed. But I cannot say how."',
      'In the end, Bank Vole went quietly, as no one would pay the service fee to hear his last words.',
      'Under a starless night sky, Least Weasel wrapped himself in yesterday\'s news hoping it wouldn\'t soon become tomorrow\'s papier-mache.',
      'Calmly adjusting fire, Corsican Nuthatch shifted from one target to the next only slowing to change magazines, never looking away.',
      '"So, we stand at the brink." Irish Hare looked down with his companions. "I see that logic and reason have already hit bottom."',
      '"Nobody told me I\'d be digging my own hole," Pool Frog complained between shovelfuls. "Sad state of affairs is what that is. Sad state."',
      'Sunglasses on, Dice Snake checked his watch again. "Why don\'t they call the flight? I have to get to the continent today."',
      'Of his job at the tollbooth, Erabu Flying Fox said, "I like to think of myself as an agent of change."',
      'Water Deer looked over the wreckage carefully before concluding that this had been the work of willful ignorance and vanity.',
      '"I believe," Rhesus Macaque said slowly, "religion is a quiet terror one should keep in the personal privacy of their own home."',
      '"Justice is not found in the barrel of a gun," American Mink argued. "It\'s found in knowing when to draw, and when to leave it holstered."',
      'Surveying the rank and file, Little Owl commented, "Collectively, you make my Onager twitch."',
      'Which to read? Kestrel pondered. "Sweet Savage Love, or Love\'s Savage Sweetness?"',
      'Kashmir Shrew flipped through a few more pages of script. "I wasn\'t aware art films had so many pie fights."',
      '"Honest to a fault." Golden Langur poured out his woes to the barista. "Does it also have to mean a lack of tact?"',
      '"A ship in the harbor leaves for England in the morning," Red Grouse said, "and we are going to be aboard her."',
      'Grey Squirrel put down the glass. "You see my dear, you give me a place to lay my heart."',
      '"Wisent, come quickly," the voice buzzed from the tin speaker. "I dropped my contact."',
      'Roe Deer waited as long as patience allowed for the crosswalk light before giving up with tragic consequences.',
      'Common Vole put down his pen and let his eyes scan the notes as his heart played the melody. "They can play this at my funeral."',
      'Asian Polecat stepped up to the microphone. "Is this thing on? I don\'t want my words actually heard. It\'s all about the look."',
      'Mountain Hare stood angry and sick on the deck. "The waves are as high as the hills of home, but the hills don\'t move."',
      'Water Shrew answered the telephone on the third ring. "If I knew the time and temperature, do you think I would actually tell you?"',
      'Spotted Quoll observed dryly, "Irony is a rubber band that never stops twanging."',
      '"Let the dice fly!" Blue Jay sang triumphant. "We have made our choice, and baby needs a new pair of shoes."',
      'Orkney Vole adjusted sunglasses and hat before stepping into the sun. "Why is my day never cloudy when I need it?"',
      '"If I had a hammer," Golden Pheasant sang, "I\'d know where I left my tool belt."',
      '"The ignorant don\'t know they\'re ignorant," Naked-rump Tomb Bat intoned. "Reminding them of it doesn\'t make them happy."',
      'Wooly Hare stopped for lunch at the diner. "Some days it seems as though work will never end."',
      '"Drill, baby, drill," chanted Black Woodpecker, "with my bill, baby, bill."',
      '"This little light of mine," St. Kilda Field Mouse observed, "is in the ultraviolet range. Not visible to the naked eye."',
      'Norwegian Rat entered the galley slowly, there was one thing and one thing only on his mind. "Coffee."',
      '"I wonder," Whiskered Bat studied the mirror. "I wonder if muttonchops would offend anyone?"',
      'Roadrunner sealed the manuscript in the box and took it to the post. Soon, the whole world would know the truth strange that it was.',
      '"Fate and necessity are mothers," Meadowlark spread his wings to the salty, sea air, "and I shall be son to neither."',
      '"In a sense we are all the products of our self-perceptions," Chimney Swift said. "It\'s horrible."',
      '"I don\'t understand," Artic Tern exclaimed. "What magic is there in this so called shortcake?"',
      'Striped Dolphin sorted through his files for the hundredth time; the auditors were coming, and hell was coming with them.',
      'White-tailed Mole paid the check for dinner and left a hefty tip. "Days like these make my tummy happy and my conscience cleaner."',
      'Rock Hyrax signed the contract grudgingly; it wasn\'t what he really wanted but, it would get his message to the masses.',
      'Sharp-shinned Hawk left the council meeting in disgust. War was coming, even if he be the one to start it.',
      '"Me and my arrow." Irish Hare took long strides out the gate. "That\'s who."',
      'Cotton-top Tamarin returned home from the hairdressers. "Now this, darling, is a statement. What do you think, in careful terms only?"',
      'North African Hedgehog trundled across the sand by way of the trenches. "If it\'s water they want, they\'ll have to come to me to get it."',
      '"I\'ve never dropped acid but," Taiga shrew adjusted his goggles, "I did spill some bicarb in the foyer."',
      'Barbary Ape considered his options. "If only I some business to take me to Seville."',
      '"Magic beans?" After a few minutes Alpine Marmot returned to the table. "No, but I have some asparagus that will do you wonders."',
      'Romanian Hamster paused a moment to reflect on current exchange rates. "Meh."',
      'Southern Birch Mouse swaggered into the yogurt bar and went straight for the extra toppings. "Hello ladies."',
      'Corsac Fox checked his boots, belts, and bullets before climbing into the saddle. "Now, to the Volga we ride! If that\'s okay with you, da?"',
      '"You say we\'re on a road to nowhere," Cypriot Mouse pointed out, "but that\'s where taking the high road sometimes gets you."',
      'Pallas\'s Cat threatened the natural order of things. That is to say, preferring chalets to shacks and cutlets to cut rate.',
      '"I\'m no connoisseur myself but," Mouflon explained, "fanaticism in any flavor is still just as bitter."',
      'Roman Mole put on as innocent a look as possible. "I swear, it\'s just a beauty mark."',
      '"Convention dictates," Bechstein\'s Bat said, "that what happens in Geneva, stays in Geneva."',
      'Garter Snake panted heavily. "Normally I cut across the park, but I hate living a cliché."',
      'Indonesian Bat pulled his sarong tight around him before going out for the morning newspaper and coffee.',
      'Iberian Lynx stumbled haltingly across her kitchen floor. Which would it be today? The chiropractor or the osteopath?',
      'Bobak Marmot hunkers down deeper in his hole and waits for the shelling to stop. Soon, unearthly dread would be replaced by unnatural fear.',
      'Common Genet stomped determinedly into the live bait shop to get the argument he was expecting.',
      'Schweizer Chicken sat down in front of the open mike, pulled his trumpet from the case and let his soul blow.',
      'Box Turtle reached his aha moment, his epiphany arrived. Paradigm shaken, he was thinking outside the shell.',
      'Lesser Mole Rat picked up the poles like the others and bore the litter with Greater Mole Rat in it. One day things would change, one day.',
      'Siberian Flying Squirrel admired her heels in the mirror, and smirked. "Now these are going to make heads turn."',
      '"Oh buttons? Buttons are easy," Long-fingered Bat spoke deftly. "Sewing on buttonholes is infinitely more difficult."',
      'Flemish Giant felt an itch between his shoulder blades. But why?',
      'Masked Booby finished the letter with a flourish. "As always, with well regard, your friendly neighborhood Watch."',
      'Chimney Swift brushed off his hat and coat, then headed for the door. "I feel lucky today. Really, really lucky."',
      'Chamois took the time to straighten the portrait on the wall, and in the end, that made all the difference.',
      'Golden Fox waited for enough light to see each blade of grass before hitting the trail hard and fast.',
      '"Let\'s doff the robes of mediocrity," implored Sei Whale, "and don the hot pants of public recognition. Now is our time."',
      'Common Hamster yelled down into the pit at Sunda Clouded Leopard, "No hard feelings, old chap! Circle of life and all that rot!"',
      'Leading the rush for the boats, Marbled Polecat held her saber high, "For King and Country, for justice and mercy! To the sea!"',
      'Russian Desman picked up the cocktail shaker and gave it the old one two. "Now this, my pet, will open your eyes for true."',
      'Risso\'s Dolphin boiled pasta as the tomato sauce merrily bubbled along. "This will be the hit of the graduation party!"',
      '"Code Orange? Code Orange?" Granada Hare cried. "I just learned Code Banana last week. What the heck is this crap?"',
      'Crested Porcupine poured another cup of coffee and buttered a biscuit. "Saturday. To the park, then. Home for tea."',
      'House Shrew moved a piece on the sand table, "Picking Republican doesn\'t make one any smarter." And he gave an evil chuckle.',
      'Swift Fox knelt on the grass and touched the stone. "I remember you. Today. And every day."',
      'Virginia Opossum lit her pipe and checked the creek level. "We might float rubber ducks in the parlor, but at least the roof don\'t leak."',
      'Agile Kangaroo Rat held the door open for his companion, and the next couple by default, and the next, and eventually got the job.',
      'Olympic Marmot stuffed frosting into each cheek before blowing out the candles. "Well, you never know..."',
      'Yellow-faced Pocket Gopher hid in shame. "Last time. I swear, it\'s the last time."',
      'Looking at the wire, Pacific Jumping Mouse made up his mind. "I\'ll stick to hurtling barrels. Why get served up as a plate of fried mice?"',
      '"Beautiful noodles?" Southern Flying Squirrel translated the menu. "I don\'t know whether to eat it or ask it out on a date."',
      'Egyptian Mongoose insisted on keeping an uneven, arrhythmic pace across the bridge so not to create a destructive resonance. Not a walk.',
      'Alpine Chipmunk expressed amazement, "If I was any more taken aback, I\'d be in front of myself."',
      '"Transit of Venus?" Cactus Mouse scoffed. "Last time I did that I ended up in traction for a month."',
      'Ringed Seal stayed on the sidewalk. "I don\'t know, fellas. I\'m not really into the whole club scene, you know?"',
      '"The only problem I have with morbid obesity," King Vulture griped, "is that it\'s not fast enough."',
      '"Haunch. Yeah, haunch." California Condor said between chews. "I love that word, don\'t you? Haunch."',
      '"Reckon on taking the long trail to the river," Sagebrush Vole drawled. "Gives us more of a chance a luring them rustlers out in the open."',
      '"You want me to hold a city with the aged, the weak, the sick and infirm?" Muscovy Duck grated. "And you call me a monster?"',
      'Banded Quail took in his surroundings, the cell, the bars and chains, the uniform and spoke softly, sadly, "Top of the world. Top of..."',
      'Spruce Grouse leaned in, venom sweet, "Morning Sunshine, eating with your squad today or shall I shoot you now and save cook the trouble?"',
      '"I try avoiding epiphanies," Brown Pelican explained. "They have a disagreeable habit of shattering all my most personal illusions."',
      'Cackling Goose shouldered his pack and moved out. "March or die, he said. Die. Sounds a lot like fly to me."',
      'Fresno Kangaroo Rat clung to a piece of wreckage floating down the river. "Live steam, dead steam. Oh, now I get it."',
      '"I don\'t need her to open pickle jars necessarily," Red Wolf spoke of his mate. "But I do need her to open the olive jar."',
      'Wood Stork held out the clipboard. "Look, company policy. Leave no door ajar, leave no jar what\'s open. Sign here."',
      '"Reload!" Screamed Cuckoo impotently at a silent firing line, tears streamed down his face from the acrid smoke. "Reload, someone, reload."',
      'Malabar Civet waited nervously, folding his napkin in an origami of anxiety, for the sommelier. "I will not be intimidated. I will not."',
      'Mockingbird eyed her customer with ill disguised contempt. "It is correct. It\'s called vanity sizing."',
      '"That has to be the saddest thing I\'ve ever heard in my life," Blue Heron admitted, and then brought the axe down in a decisive blow.',
      '"Trust me," Sicilian Shrew smiled, "if I could step any further away from this, I wouldn\'t even be here."',
      '"It\'s got no zip, no zing, no pop!" Brown Bear critiqued the show. "Your chorus line is like a deadline. Seen better moves in a tar pit."',
      'Natterjack Toad looked in the mirror, said in a small voice, "May not be ripped and shredded, but I got smothered and covered down pat."',
      '"Don\'t know why they call it balmy," Maya Mouse fanned himself. "There\'s nothing balm-like about this weather. Soothed we are not."',
      'Every morning Nancy Ma\'s Night Monkey could be found by the river acting out his strange pantomime and mouthing the words, "Kill him!"',
      'Gray Dwarf Mouse looked at his friends. "Which will it be, life of the samurai or mining?"',
      'Cool under fire, Wildcat leapt from the gunwale of her ship to the other\'s with the grace of a dancer or cutlass carrying cat burglar.',
      '"Sweet comfort," Soprano Pipistrelle languished in his cool cave, "and green, too."',
      'After laying in the wagon rut for some time, European Adder decided it was no cooler there either and Scandinavia looked better and better.',
      '"Fear?" Hopi Chipmunk checked the telegrams on his desk. "Fear gets votes. Rationality doesn\'t win over anything."',
      '"He ain\'t the sharpest bulb in the deck," Eastern Wolf watched his son go by, "but that\'ll do, that will do."',
      '"Freedom isn\'t free," Rock Squirrel cautioned, "but it\'s cheap compared to being an irrational, uninformed idiot.Now light my sparkler."',
      'Southern White breasted Hedgehog turned the key in the lock and then left it there. "Storm\'s coming. Won\'t be anything to unlock later."',
      'Spiny Mouse looked up at his rescuers. "I dared the grey oaf, just dared him, you know? Then the sun went out."',
      'Jaguar stopped chewing for a moment and looked at his mate. "Tell me again why we\'re eating leafy greens."',
      'Putting his ear to the door, Little Cuckoo winced. "Either the wind is crying or your mother\'s coming up the walk."',
      '"Winter never gets here soon enough," Caribbean Coot complained. "I miss temperatures in the low nineties."',
      'After close inspection, Musk Shrew reached into the medicine cabinet for his favorite aftershave lotion. "Wait, what am I doing? Sheesh."',
      '"In vino Veritas?" Crab-eating Macaque winked. "In Scotch Veritas is more to my liking. And you\'ll get better truths at that."',
      '"Mother never did master English," Algerian Mouse explained. "But she did beat it into submission."',
      '"My center has collapsed. Reserves gone. Lines in disarray. But one thing to do." Spotted Souslik radioed. "Cue the dance number."',
      'With a moue of disappointment, Fulvous Whistling Duck faced her accusers. "Why? What is wrong with my face that you should hate me so?"',
      '"Give me liberty," Osprey orated, "and I give you yours. Protect my freedom and I\'ll protect yours. Give me equality and be my equal."',
      '"I don\'t understand," Wood Lemming looked down at Balkan Mole on the ground. "I didn\'t poison either cup."',
      'Botta\'s Serotine was inclined to recommend the baklava. It went well with the black coffee.',
      'Ocellated Quail walked away from the ice cream shop happily. "They always give me an extra scoop because they remember my ex-wife."',
      '"Cursed wretched earth!" Calabria Pine Vole kicked the dust that had been his farm. "No seeds of change, nor change of seed will save us."',
      '"What now squeaky wheel?" Golden-capped Fruit Bat sneered at his defunct chariot by the side of the road. "The grease pot. It is dry."',
      'Mountain Beaver read the report solemnly. "Unfurl the yellow flag and hoist it aloft. The ship is sick, and no port will have us make call."',
      '"I have a surfeit of fair weather friends," Uinta Chipmunk stomped. "What I need are holiday dinner friends!"',
      '"Lowland Gorilla pushed her cart down the frozen food aisle. "I hate it when the doors fog over and I can\'t see anything."',
      'Mustang scanned a sea of green lights across the panel and grew impatient. "C\'mon, let\'s light this candle."',
      '"Those who can\'t teach," Beech Marten pointed out, "are often those who can\'t learn either."',
      'Furious, Weddell Seal scribbled, and checked boxes. "I can\'t believe how much trouble it is to prove who I am to get proof of who I am."',
      '"They say familiarity breeds contempt," reminded Pleasant Gerbil. "But I find some breeds I\'m familiar with quite contemptible."',
      '"We don\'t play favorites." Little Brown Bat spun up another record, "but we do take requests."',
      '"I used to be a grammarian like you," Woolly Dormouse compared his present life, "until I took an adverb to the knee."',
      'Broken wing and crooked back, Masked Duck crossed the street on stiff legs clutching the gun murderously. "You, you\'re despicable."',
      'Sweat beading, Roadrunner, acutely aware of the second hand sweep towards inevitably, thought furiously. Which? Red or green? Red or green?',
      'Holstein Cow lay her neck across the block bewildered. "I knew they were revolting but, I didn\'t know the fowl had actually succeeded."',
      '"Hmm," Elf Owl checked the manual then asked Gyrfalcon, "Do we add dither or jitter to the signal now?"',
      'Hokkaido Wolf trotted into the woods and marked an unknown grave. "I told you cat. You ask too many questions."'
    ];
    var useQuote = Math.floor(Math.random() * useQuotes.length);
    document.getElementById("quoted").innerHTML = useQuotes[useQuote];

    function fadeIn() {
      var el = document.getElementById("quoted");
      el.style.opacity = "0";

      var last = +new Date();
      var tick = function () {
        el.style.opacity = +el.style.opacity + (new Date() - last) / 4000;
        last = +new Date();

        if (+el.style.opacity < 1) {
          (window.requestAnimationFrame && requestAnimationFrame(tick)) || setTimeout(tick, 16);
        }
      };
      tick();
    }
    fadeIn();

    document.getElementById("tweet").addEventListener("click", function tweetIt() {
      var randomNumber = Math.floor(Math.random() * (useQuotes.length));
      window.open("https://twitter.com/intent/tweet?text=" + useQuotes[useQuote]);
    });
  }
};